package com.mycompany.sunrisedentalserviceapp.view;

import com.mycompany.sunrisedentalserviceapp.DatabaseConnection;
import javax.swing.JOptionPane;

public class PatientView extends javax.swing.JFrame {

    public PatientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Management - Sunrise Dental Service");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setText("Patient Registration & Management");

        lblPatientId.setText("Patient ID:");

        lblFullName.setText("Full Name:");

        lblAge.setText("Age:");

        lblContact.setText("Contact No:");

        lblAddress.setText("Address:");

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientId)
                            .addComponent(lblFullName)
                            .addComponent(lblAge)
                            .addComponent(lblContact)
                            .addComponent(lblAddress))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatientId)
                            .addComponent(txtFullName)
                            .addComponent(txtAge)
                            .addComponent(txtContact)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegister)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientId)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String patientId = txtPatientId.getText().trim();
        String fullName = txtFullName.getText().trim();
        String age = txtAge.getText().trim();
        String contact = txtContact.getText().trim();
        String address = txtAddress.getText().trim();

        if (patientId.isEmpty() || fullName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill required fields!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.sql.Connection con = DatabaseConnection.getInstance().getConnection();
            String sql = "INSERT INTO patient VALUES (?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, patientId);
            pstm.setString(2, fullName);
            pstm.setInt(3, Integer.parseInt(age));
            pstm.setString(4, contact);
            pstm.setString(5, address);

            int rows = pstm.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Patient Registered Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnClearActionPerformed(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String patientId = txtPatientId.getText().trim();
        String fullName = txtFullName.getText().trim();
        String age = txtAge.getText().trim();
        String contact = txtContact.getText().trim();
        String address = txtAddress.getText().trim();

        if (patientId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Patient ID to update!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.sql.Connection con = DatabaseConnection.getInstance().getConnection();
            String sql = "UPDATE patient SET name=?, age=?, contact=?, address=? WHERE patient_id=?";
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, fullName);
            pstm.setInt(2, Integer.parseInt(age));
            pstm.setString(3, contact);
            pstm.setString(4, address);
            pstm.setString(5, patientId);

            int rows = pstm.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Patient Updated Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnClearActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Patient ID Not Found!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                         

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String patientId = txtPatientId.getText().trim();

        if (patientId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Patient ID to delete!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this patient?", "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection con = DatabaseConnection.getInstance().getConnection();
                String sql = "DELETE FROM patient WHERE patient_id = ?";
                java.sql.PreparedStatement pstm = con.prepareStatement(sql);
                pstm.setString(1, patientId);

                int rows = pstm.executeUpdate();

                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Patient Deleted Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    btnClearActionPerformed(null);
                } else {
                    JOptionPane.showMessageDialog(this, "Patient ID Not Found!", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }                                         

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txtPatientId.setText("");
        txtFullName.setText("");
        txtAge.setText("");
        txtContact.setText("");
        txtAddress.setText("");
        txtPatientId.requestFocus();
    }                                        

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration                   
}